"use client";

import { useState } from "react";
import { Loader2, ShoppingCart, RotateCcw, ChevronDown, Copy, Check } from "lucide-react";
import ToolLayout from "@/components/shared/ToolLayout";
import AdSlot from "@/components/shared/AdSlot";
import { useLanguage } from "@/lib/LanguageContext";

interface Meal {
  type: string;
  name: string;
  calories: number;
  protein: number;
  carbs: number;
  fat: number;
  ingredients: string[];
}

interface DayPlan {
  day: string;
  totalCalories: number;
  meals: Meal[];
}

interface MealPlan {
  weekSummary: { avgDailyCalories: number; avgProtein: number; avgCarbs: number; avgFat: number };
  days: DayPlan[];
  shoppingList: Record<string, string[]>;
}

export default function MealPlanGeneratorPage() {
  const { lang, t } = useLanguage();

  const GOALS = [
    { value: "fat-loss",    label: t("mp_goal_fl") },
    { value: "muscle-gain", label: t("mp_goal_mg") },
    { value: "maintenance", label: t("mp_goal_mt") },
    { value: "vegetarian",  label: t("mp_goal_vg") },
  ];

  const RESTRICTIONS_EN = ["Gluten-free", "Dairy-free", "Nut-free", "Halal"];
  const RESTRICTIONS_ZH = ["无麸质", "无乳制品", "无坚果", "清真"];
  const RESTRICTIONS = lang === "zh" ? RESTRICTIONS_ZH : RESTRICTIONS_EN;

  const [goal, setGoal] = useState("fat-loss");
  const [calories, setCalories] = useState(1800);
  const [mealsPerDay, setMealsPerDay] = useState(3);
  const [restrictions, setRestrictions] = useState<string[]>([]);
  const [status, setStatus] = useState<"idle" | "loading" | "done" | "error">("idle");
  const [plan, setPlan] = useState<MealPlan | null>(null);
  const [expandedDay, setExpandedDay] = useState<string | null>(null);
  const [showShopping, setShowShopping] = useState(false);
  const [copiedPlan, setCopiedPlan] = useState(false);

  const toggleRestriction = (r: string) =>
    setRestrictions((prev) => (prev.includes(r) ? prev.filter((x) => x !== r) : [...prev, r]));

  const generate = async () => {
    setStatus("loading");
    setPlan(null);
    setExpandedDay(null);
    try {
      const res = await fetch("/api/generate-meal-plan", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ goal, calories, mealsPerDay, restrictions, lang }),
      });
      if (!res.ok) throw new Error();
      const reader = res.body!.getReader();
      const decoder = new TextDecoder();
      let buffer = "", fullText = "";
      while (true) {
        const { done, value } = await reader.read();
        if (done) break;
        buffer += decoder.decode(value, { stream: true });
        const lines = buffer.split("\n"); buffer = lines.pop() ?? "";
        for (const line of lines) {
          if (line.startsWith("data: ")) {
            const payload = line.slice(6).trim();
            if (payload === "[DONE]") break;
            try { const { text } = JSON.parse(payload); fullText += text; try { const p: MealPlan = JSON.parse(fullText); setPlan(p); setExpandedDay(p.days[0]?.day ?? null); } catch {} } catch {}
          }
        }
      }
      setStatus("done");
    } catch { setStatus("error"); }
  };

  const reset = () => { setStatus("idle"); setPlan(null); setExpandedDay(null); };

  const copyPlan = async () => {
    if (!plan) return;
    const lines: string[] = [
      lang === "zh" ? "📅 7天饮食计划" : "📅 7-Day Meal Plan",
      lang === "zh"
        ? `目标：${goal} | 每日 ${calories} kcal | 每天 ${mealsPerDay} 餐`
        : `Goal: ${goal} | ${calories} kcal/day | ${mealsPerDay} meals/day`,
      "",
    ];
    for (const day of plan.days) {
      lines.push(`── ${day.day} (${day.totalCalories} kcal) ──`);
      for (const meal of day.meals) {
        lines.push(`  ${meal.type}: ${meal.name} — ${meal.calories} kcal`);
      }
      lines.push("");
    }
    lines.push(lang === "zh" ? "— NutriTools.com 生成" : "— Generated by NutriTools.com");
    await navigator.clipboard.writeText(lines.join("\n"));
    setCopiedPlan(true);
    setTimeout(() => setCopiedPlan(false), 2000);
  };

  return (
    <ToolLayout title={t("mp_title")} description={t("mp_desc")} badge={t("mp_badge")}>
      {/* Form */}
      <div className="max-w-xl mx-auto">
        <div className="bg-white border border-gray-100 rounded-2xl p-6 shadow-sm space-y-6">
          {/* Goal */}
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-2">{t("mp_goal")}</label>
            <div className="flex flex-wrap gap-2">
              {GOALS.map((g) => (
                <button key={g.value} onClick={() => setGoal(g.value)}
                  className={`px-4 py-2 rounded-lg text-sm font-medium transition-colors ${goal === g.value ? "bg-green-600 text-white" : "bg-gray-100 text-gray-600 hover:bg-gray-200"}`}>
                  {g.label}
                </button>
              ))}
            </div>
          </div>

          {/* Calories */}
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-2">
              {t("mp_cal_label")} <span className="text-green-600 font-semibold">{calories} kcal</span>
            </label>
            <input type="range" min={1200} max={3500} step={50} value={calories}
              onChange={(e) => setCalories(Number(e.target.value))} className="w-full accent-green-600" />
            <div className="flex justify-between text-xs text-gray-400 mt-1"><span>1,200</span><span>3,500</span></div>
          </div>

          {/* Meals per day */}
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-2">{t("mp_meals_label")}</label>
            <div className="flex gap-2">
              {[3, 4, 5].map((n) => (
                <button key={n} onClick={() => setMealsPerDay(n)}
                  className={`flex-1 py-2 rounded-lg text-sm font-medium transition-colors ${mealsPerDay === n ? "bg-green-600 text-white" : "bg-gray-100 text-gray-600 hover:bg-gray-200"}`}>
                  {lang === "zh" ? `${n}餐` : `${n} meals`}
                </button>
              ))}
            </div>
          </div>

          {/* Restrictions */}
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-2">{t("mp_restrict_label")}</label>
            <div className="flex flex-wrap gap-2">
              {RESTRICTIONS.map((r) => (
                <button key={r} onClick={() => toggleRestriction(r)}
                  className={`px-3 py-1.5 rounded-lg text-xs font-medium transition-colors ${restrictions.includes(r) ? "bg-green-100 text-green-700 border border-green-200" : "bg-gray-100 text-gray-500 hover:bg-gray-200"}`}>
                  {restrictions.includes(r) ? "✓ " : ""}{r}
                </button>
              ))}
            </div>
          </div>

          <div className="sticky bottom-0 sm:static bg-white/95 sm:bg-transparent backdrop-blur-sm sm:backdrop-blur-none -mx-1 px-1 pb-3 sm:pb-0">
            <button onClick={generate} disabled={status === "loading"}
              className="w-full flex items-center justify-center gap-2 px-5 py-3.5 bg-green-600 hover:bg-green-700 disabled:bg-green-300 text-white font-semibold rounded-xl transition-colors">
              {status === "loading" ? (<><Loader2 className="w-4 h-4 animate-spin" />{t("mp_btn_loading")}</>) : t("mp_btn")}
            </button>
            <p className="mt-2 text-xs text-gray-400 text-center flex items-center justify-center gap-1">
              <span className="text-green-500">✓</span> {t("no_signup_hint")}
            </p>
          </div>
        </div>
      </div>

      {/* Error */}
      {status === "error" && (
        <div className="max-w-xl mx-auto mt-6 p-4 bg-red-50 border border-red-100 rounded-xl text-center">
          <p className="text-red-600 font-medium">{t("mp_error")}</p>
          <button onClick={reset} className="mt-2 text-sm text-red-500 hover:underline">{t("mp_retry")}</button>
        </div>
      )}

      {/* Results */}
      {plan && status === "done" && (
        <div className="mt-10 space-y-6">
          {/* Week summary */}
          <div className="grid grid-cols-2 md:grid-cols-4 gap-3">
            {[
              { label: t("mp_avg_cal"),  value: plan.weekSummary.avgDailyCalories, unit: "kcal" },
              { label: t("mp_avg_prot"), value: plan.weekSummary.avgProtein,       unit: "g" },
              { label: t("mp_avg_carb"), value: plan.weekSummary.avgCarbs,         unit: "g" },
              { label: t("mp_avg_fat"),  value: plan.weekSummary.avgFat,           unit: "g" },
            ].map(({ label, value, unit }) => (
              <div key={label} className="bg-green-50 border border-green-100 rounded-xl p-4 text-center">
                <div className="text-2xl font-bold text-gray-900">{value}<span className="text-sm font-normal text-gray-500 ml-1">{unit}</span></div>
                <div className="text-xs text-gray-500 mt-0.5">{label}</div>
              </div>
            ))}
          </div>

          {/* Days */}
          <div className="space-y-2">
            {plan.days.map((dayPlan) => (
              <div key={dayPlan.day} className="border border-gray-100 rounded-2xl overflow-hidden">
                <button onClick={() => setExpandedDay(expandedDay === dayPlan.day ? null : dayPlan.day)}
                  className="w-full flex items-center justify-between px-5 py-4 bg-white hover:bg-gray-50 transition-colors">
                  <div className="flex items-center gap-3">
                    <span className="font-semibold text-gray-900">{dayPlan.day}</span>
                    <span className="text-sm text-gray-400">{dayPlan.totalCalories} kcal</span>
                  </div>
                  <ChevronDown className={`w-4 h-4 text-gray-400 transition-transform ${expandedDay === dayPlan.day ? "rotate-180" : ""}`} />
                </button>
                {expandedDay === dayPlan.day && (
                  <div className="px-5 pb-4 space-y-3 border-t border-gray-50">
                    {dayPlan.meals.map((meal, i) => (
                      <div key={i} className="bg-gray-50 rounded-xl p-4">
                        <div className="flex items-start justify-between mb-1">
                          <div>
                            <span className="text-xs font-semibold text-gray-400 uppercase tracking-wide">{meal.type}</span>
                            <p className="font-medium text-gray-800 mt-0.5">{meal.name}</p>
                          </div>
                          <span className="text-sm font-semibold text-gray-600 ml-4 shrink-0">{meal.calories} kcal</span>
                        </div>
                        <div className="flex gap-3 mt-2">
                          {[
                            { label: lang === "zh" ? "蛋白质" : "P", value: meal.protein, color: "text-green-600" },
                            { label: lang === "zh" ? "碳水" : "C",   value: meal.carbs,   color: "text-amber-600" },
                            { label: lang === "zh" ? "脂肪" : "F",   value: meal.fat,     color: "text-blue-600" },
                          ].map(({ label, value, color }) => (
                            <span key={label} className={`text-xs font-medium ${color} bg-white px-2 py-0.5 rounded-md border border-gray-100`}>
                              {label}: {value}g
                            </span>
                          ))}
                        </div>
                      </div>
                    ))}
                  </div>
                )}
              </div>
            ))}
          </div>

          {/* Shopping list */}
          {plan.shoppingList && (
            <div className="border border-gray-100 rounded-2xl overflow-hidden">
              <button onClick={() => setShowShopping(!showShopping)} className="w-full flex items-center justify-between px-5 py-4 bg-white hover:bg-gray-50">
                <div className="flex items-center gap-2">
                  <ShoppingCart className="w-4 h-4 text-green-600" />
                  <span className="font-semibold text-gray-900">{t("mp_shopping")}</span>
                </div>
                <ChevronDown className={`w-4 h-4 text-gray-400 transition-transform ${showShopping ? "rotate-180" : ""}`} />
              </button>
              {showShopping && (
                <div className="px-5 pb-5 border-t border-gray-50 grid sm:grid-cols-2 md:grid-cols-3 gap-4 pt-4">
                  {Object.entries(plan.shoppingList).map(([category, items]) =>
                    items.length > 0 ? (
                      <div key={category}>
                        <h4 className="text-xs font-semibold text-gray-500 uppercase tracking-wide mb-2 capitalize">{category}</h4>
                        <ul className="space-y-1">
                          {items.map((item) => (
                            <li key={item} className="text-sm text-gray-700 flex items-start gap-1.5">
                              <span className="text-green-500 mt-0.5">•</span> {item}
                            </li>
                          ))}
                        </ul>
                      </div>
                    ) : null
                  )}
                </div>
              )}
            </div>
          )}

          {/* Actions */}
          <div className="flex gap-3">
            <button onClick={reset} className="flex items-center gap-2 px-4 py-2.5 border border-gray-200 hover:border-gray-300 text-gray-600 text-sm font-medium rounded-lg transition-colors">
              <RotateCcw className="w-4 h-4" /> {t("mp_reset")}
            </button>
            <button onClick={copyPlan} className="flex items-center gap-2 px-4 py-2.5 border border-gray-200 hover:border-green-200 hover:text-green-700 text-gray-600 text-sm font-medium rounded-lg transition-colors">
              {copiedPlan
                ? <><Check className="w-4 h-4 text-green-500" />{t("copy_result_done")}</>
                : <><Copy className="w-4 h-4" />{t("mp_copy_plan")}</>}
            </button>
          </div>

          <AdSlot position="meal-plan-results" size="728x90" />
        </div>
      )}
    </ToolLayout>
  );
}
