"use client";

import { useState } from "react";
import { Loader2, Copy, Check, ArrowRight } from "lucide-react";
import ToolLayout from "@/components/shared/ToolLayout";
import AdSlot from "@/components/shared/AdSlot";
import { useLanguage } from "@/lib/LanguageContext";

interface Substitute {
  name: string;
  ratio: string;
  matchScore: number;
  isBestMatch: boolean;
  pros: string[];
  cons: string[];
  notes: string;
}

interface SubstitutionResult {
  original: string;
  substitutes: Substitute[];
  tips: string;
}

const POPULAR_EN = [
  { ingredient: "butter", context: "baking", reason: "healthier option" },
  { ingredient: "eggs", context: "cake", reason: "vegan" },
  { ingredient: "milk", context: "cookies", reason: "dairy-free" },
  { ingredient: "flour", context: "baking", reason: "gluten-free" },
  { ingredient: "sugar", context: "baking", reason: "healthier option" },
  { ingredient: "mayonnaise", context: "salad", reason: "lower calories" },
];

const POPULAR_ZH = [
  { ingredient: "黄油", context: "烘焙", reason: "更健康" },
  { ingredient: "鸡蛋", context: "蛋糕", reason: "纯素食" },
  { ingredient: "牛奶", context: "饼干", reason: "无乳糖" },
  { ingredient: "面粉", context: "烘焙", reason: "无麸质" },
  { ingredient: "白砂糖", context: "烘焙", reason: "更健康" },
  { ingredient: "蛋黄酱", context: "沙拉", reason: "低热量" },
];

export default function FoodSubstitutionFinderPage() {
  const { lang, t } = useLanguage();

  const REASONS = [
    { value: "allergy",         label: t("fs_reason_allergy") },
    { value: "out-of-stock",    label: t("fs_reason_stock") },
    { value: "dietary",         label: t("fs_reason_diet") },
    { value: "healthier option",label: t("fs_reason_health") },
  ];

  const POPULAR = lang === "zh" ? POPULAR_ZH : POPULAR_EN;

  const [ingredient, setIngredient] = useState("");
  const [context, setContext] = useState("");
  const [reason, setReason] = useState("allergy");
  const [status, setStatus] = useState<"idle" | "loading" | "done" | "error">("idle");
  const [result, setResult] = useState<SubstitutionResult | null>(null);
  const [copiedIdx, setCopiedIdx] = useState<number | null>(null);
  const [copiedAll, setCopiedAll] = useState(false);

  const findSubstitutes = async () => {
    if (!ingredient.trim()) return;
    setStatus("loading");
    setResult(null);
    try {
      const res = await fetch("/api/find-substitutions", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ ingredient, context, reason, lang }),
      });
      if (!res.ok) throw new Error();
      const reader = res.body!.getReader();
      const decoder = new TextDecoder();
      let buffer = "", fullText = "";
      while (true) {
        const { done, value } = await reader.read();
        if (done) break;
        buffer += decoder.decode(value, { stream: true });
        const lines = buffer.split("\n"); buffer = lines.pop() ?? "";
        for (const line of lines) {
          if (line.startsWith("data: ")) {
            const payload = line.slice(6).trim();
            if (payload === "[DONE]") break;
            try { const { text } = JSON.parse(payload); fullText += text; try { setResult(JSON.parse(fullText)); } catch {} } catch {}
          }
        }
      }
      setStatus("done");
    } catch { setStatus("error"); }
  };

  const copyRatio = async (idx: number, ratio: string) => {
    await navigator.clipboard.writeText(ratio);
    setCopiedIdx(idx);
    setTimeout(() => setCopiedIdx(null), 1500);
  };

  const copyAll = async () => {
    if (!result) return;
    const lines: string[] = [
      lang === "zh"
        ? `🔄 「${result.original}」的替换方案${context ? ` (${context})` : ""}`
        : `🔄 Substitutes for "${result.original}"${context ? ` in ${context}` : ""}`,
      "",
    ];
    for (const sub of result.substitutes) {
      lines.push(`${sub.isBestMatch ? "⭐ " : ""}${sub.name} (${sub.matchScore}%)`);
      lines.push(`   ${sub.ratio}`);
      if (sub.pros.length) lines.push(`   ✓ ${sub.pros.join(" · ")}`);
      if (sub.notes) lines.push(`   💡 ${sub.notes}`);
      lines.push("");
    }
    if (result.tips) lines.push(`💡 ${result.tips}`);
    lines.push(lang === "zh" ? "— NutriTools.com 生成" : "— Generated by NutriTools.com");
    await navigator.clipboard.writeText(lines.join("\n"));
    setCopiedAll(true);
    setTimeout(() => setCopiedAll(false), 2000);
  };

  return (
    <ToolLayout title={t("fs_title")} description={t("fs_desc")} badge={t("fs_badge")}>
      {/* Input hero */}
      <div className="bg-gradient-to-br from-green-50 to-emerald-50 border border-green-100 rounded-2xl p-6 md:p-8 mb-8">
        <p className="text-sm font-medium text-green-700 mb-4">{t("fs_prompt")}</p>

        <div className="flex flex-col sm:flex-row gap-3 mb-4">
          <input value={ingredient} onChange={(e) => setIngredient(e.target.value)}
            placeholder={t("fs_ing_placeholder")}
            className="flex-1 px-4 py-3 rounded-xl border border-green-200 bg-white focus:outline-none focus:ring-2 focus:ring-green-500/30 focus:border-green-500 text-sm text-gray-800 placeholder-gray-400" />
          <span className="text-sm text-gray-400 self-center shrink-0">{t("fs_in")}</span>
          <input value={context} onChange={(e) => setContext(e.target.value)}
            placeholder={t("fs_ctx_placeholder")}
            className="flex-1 px-4 py-3 rounded-xl border border-green-200 bg-white focus:outline-none focus:ring-2 focus:ring-green-500/30 focus:border-green-500 text-sm text-gray-800 placeholder-gray-400" />
        </div>

        {/* Reason */}
        <div className="flex flex-wrap gap-2 mb-5">
          <span className="text-xs text-gray-500 self-center mr-1">{t("fs_reason")}</span>
          {REASONS.map((r) => (
            <button key={r.value} onClick={() => setReason(r.value)}
              className={`px-3 py-1.5 rounded-lg text-xs font-medium transition-colors ${reason === r.value ? "bg-green-600 text-white" : "bg-white text-gray-600 border border-green-100 hover:border-green-200"}`}>
              {r.label}
            </button>
          ))}
        </div>

        <div className="flex flex-col sm:flex-row items-start sm:items-center gap-3">
          <button onClick={findSubstitutes} disabled={status === "loading" || !ingredient.trim()}
            className="flex items-center justify-center gap-2 px-6 py-3 bg-green-600 hover:bg-green-700 disabled:bg-green-300 text-white font-semibold rounded-xl transition-colors w-full sm:w-auto">
            {status === "loading" ? (<><Loader2 className="w-4 h-4 animate-spin" />{t("fs_btn_loading")}</>) : (<>{t("fs_btn")}<ArrowRight className="w-4 h-4" /></>)}
          </button>
          <p className="text-xs text-gray-400 flex items-center gap-1">
            <span className="text-green-500">✓</span> {t("no_signup_hint")}
          </p>
        </div>

        {/* Popular searches */}
        <div className="mt-5 flex flex-wrap gap-2 items-center">
          <span className="text-xs text-gray-400">{t("try_example")}:</span>
          {POPULAR.map((p, i) => (
            <button key={`${p.ingredient}-${p.context}`}
              onClick={() => { setIngredient(p.ingredient); setContext(p.context); setReason(p.reason); }}
              className={`text-xs px-2.5 py-1 border rounded-full transition-colors ${
                i === 0
                  ? "bg-green-50 border-green-200 text-green-700 hover:bg-green-100"
                  : "bg-white border-gray-200 hover:border-green-300 text-gray-600"
              }`}>
              {p.ingredient} — {p.context}
            </button>
          ))}
        </div>
      </div>

      {/* Error */}
      {status === "error" && (
        <div className="p-4 bg-red-50 border border-red-100 rounded-xl text-center">
          <p className="text-red-600 font-medium text-sm">{t("fs_error")}</p>
        </div>
      )}

      {/* Loading */}
      {status === "loading" && (
        <div className="space-y-4">
          {[...Array(3)].map((_, i) => <div key={i} className="h-40 bg-gray-100 rounded-2xl animate-pulse" />)}
        </div>
      )}

      {/* Results */}
      {result && status === "done" && (
        <div className="space-y-4">
          <div className="flex items-center justify-between flex-wrap gap-2">
            <p className="text-sm text-gray-500">
              {t("fs_found").replace("{n}", String(result.substitutes.length))}{" "}
              <strong className="text-gray-800">{result.original}</strong>
              {context ? ` — ${context}` : ""}
            </p>
            <button
              onClick={copyAll}
              className="flex items-center gap-1 text-xs text-gray-400 hover:text-gray-700 transition-colors px-2.5 py-1.5 border border-gray-200 hover:border-gray-300 rounded-lg"
            >
              {copiedAll
                ? <><Check className="w-3 h-3 text-green-500" />{t("copy_result_done")}</>
                : <><Copy className="w-3 h-3" />{t("fs_copy_all")}</>}
            </button>
          </div>

          {result.substitutes.map((sub, idx) => (
            <div key={idx} className={`bg-white rounded-2xl border p-5 transition-shadow hover:shadow-md ${sub.isBestMatch ? "border-green-300 shadow-sm" : "border-gray-100"}`}>
              <div className="flex items-start justify-between mb-3">
                <div className="flex items-center gap-2">
                  <h3 className="font-semibold text-gray-900">{sub.name}</h3>
                  {sub.isBestMatch && <span className="text-xs font-semibold bg-green-100 text-green-700 px-2 py-0.5 rounded-full">{t("fs_best")}</span>}
                  <span className="text-xs text-gray-400 bg-gray-100 px-2 py-0.5 rounded-full">{sub.matchScore}%</span>
                </div>
                <button onClick={() => copyRatio(idx, sub.ratio)}
                  className="flex items-center gap-1 text-xs text-gray-400 hover:text-gray-700 transition-colors px-2 py-1 border border-gray-100 rounded-lg">
                  {copiedIdx === idx ? (<><Check className="w-3 h-3 text-green-500" />{t("fs_copied")}</>) : (<><Copy className="w-3 h-3" />{t("fs_copy")}</>)}
                </button>
              </div>
              <p className="text-sm font-mono text-gray-700 bg-gray-50 px-3 py-2 rounded-lg mb-3">{sub.ratio}</p>
              <div className="grid sm:grid-cols-2 gap-3">
                <div>{sub.pros.map((pro, i) => <p key={i} className="text-xs text-green-700 flex gap-1 mb-1"><span>✓</span>{pro}</p>)}</div>
                <div>{sub.cons.map((con, i) => <p key={i} className="text-xs text-red-500 flex gap-1 mb-1"><span>✗</span>{con}</p>)}</div>
              </div>
              {sub.notes && <p className="mt-3 text-xs text-gray-500 italic">{sub.notes}</p>}
            </div>
          ))}

          {result.tips && (
            <div className="bg-blue-50 border border-blue-100 rounded-xl p-4">
              <p className="text-xs font-semibold text-blue-700 mb-1">{t("fs_tip_title")}</p>
              <p className="text-sm text-blue-800">{result.tips}</p>
            </div>
          )}

          <AdSlot position="substitution-results" size="728x90" />
        </div>
      )}

      {/* SEO content */}
      <div className="mt-16 max-w-3xl mx-auto">
        <h2 className="text-2xl font-bold text-gray-900 mb-4">{t("fs_seo_h2")}</h2>
        <p className="text-gray-600 text-sm leading-relaxed mb-6">{t("fs_seo_p")}</p>
        <div className="grid sm:grid-cols-2 gap-4">
          {[
            { title: lang === "zh" ? "烘焙黄油替换指南"   : "Butter Substitutes for Baking",   href: "/food-substitution-finder/butter-substitute-for-baking" },
            { title: lang === "zh" ? "烘焙鸡蛋替换指南"   : "Egg Substitutes for Baking",       href: "/food-substitution-finder/egg-substitute-for-baking" },
            { title: lang === "zh" ? "牛奶替换指南"       : "Milk Substitutes",                 href: "/food-substitution-finder/milk-substitute" },
            { title: lang === "zh" ? "糖替换指南"         : "Sugar Substitutes",                href: "/food-substitution-finder/sugar-substitute" },
            { title: lang === "zh" ? "泡打粉替换指南"     : "Baking Powder Substitutes",        href: "/food-substitution-finder/baking-powder-substitute" },
            { title: lang === "zh" ? "淡奶油替换指南"     : "Heavy Cream Substitutes",          href: "/food-substitution-finder/heavy-cream-substitute" },
            { title: lang === "zh" ? "香草精替换指南"     : "Vanilla Extract Substitutes",      href: "/food-substitution-finder/vanilla-extract-substitute" },
            { title: lang === "zh" ? "植物油替换指南"     : "Vegetable Oil Substitutes",        href: "/food-substitution-finder/vegetable-oil-substitute" },
            { title: lang === "zh" ? "酸奶油替换指南"     : "Sour Cream Substitutes",           href: "/food-substitution-finder/sour-cream-substitute" },
          ].map(({ title, href }) => (
            <a key={href} href={href}
              className="flex items-center justify-between px-4 py-3 bg-white border border-gray-100 rounded-xl hover:border-green-200 hover:bg-green-50/30 transition-colors group">
              <span className="text-sm font-medium text-gray-700 group-hover:text-green-700">{title}</span>
              <ArrowRight className="w-4 h-4 text-gray-300 group-hover:text-green-500 transition-colors" />
            </a>
          ))}
        </div>
      </div>
    </ToolLayout>
  );
}
